const data = [
  {
    HCP_NAME: "ROBERT D YOO",
    PDRP: "N",
    TERRITORY: "PHOENIX, AZ",
    REGION: "SOUTHWEST",
    CHILD_NAME: "IRONWOOD CANCER AND RESEARCH CENTERS-CHANDLER 1",
    PARENT_NAME: "IRONWOOD CANCER AND RESEARCH CENTER-CHANDLER II",
  },
  {
    HCP_NAME: "KRISZTINA I LARSON",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "THE ONCOLOGY INSTITUTE CERRITOS-CORPORATE OFFICE",
    PARENT_NAME: "THE ONCOLOGY INSTITUTE OF HOPE AND INNOVATION ADMIN OFFICE",
  },
  {
    HCP_NAME: "AMARA G NANDIKOLLA",
    PDRP: "N",
    TERRITORY: "OKLAHOMA CITY, OK",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "UTICA PARK CLINIC",
    PARENT_NAME: "UTICA PARK CLINIC",
  },
  {
    HCP_NAME: "SMITH GIRI",
    PDRP: "N",
    TERRITORY: "BIRMINGHAM, AL",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "UNIVERSITY OF ALABAMA HOSPITAL",
    PARENT_NAME: "THE KIRKLIN CLINIC OF UAB HOSPITAL",
  },
  {
    HCP_NAME: "JOSE IGNACIO MAYORDOMO",
    PDRP: "N",
    TERRITORY: "DENVER, CO",
    REGION: "SOUTHWEST",
    CHILD_NAME: "UNIVERSITY OF COLORADO HOSPITAL",
    PARENT_NAME: "UNIVERSITY OF COLORADO HOSPITAL",
  },
  {
    HCP_NAME: "LYNETTE GRAHAM",
    PDRP: "NULL",
    TERRITORY: "CHARLESTON, SC",
    REGION: "SOUTHEAST",
    CHILD_NAME:
      "COASTAL CANCER CENTER ASSOCIATED MEDICAL SPECIALISTS MYRTLE BEACH",
    PARENT_NAME:
      "COASTAL CANCER CENTER ASSOCIATED MEDICAL SPECIALISTS MYRTLE BEACH",
  },
  {
    HCP_NAME: "MADELINE S WOOD",
    PDRP: "N",
    TERRITORY: "HARTFORD, CT",
    REGION: "NORTHEAST",
    CHILD_NAME: "YALE-NEW HAVEN HOSPITAL",
    PARENT_NAME: "YALE-NEW HAVEN HOSPITAL",
  },
  {
    HCP_NAME: "EMILY Z STOREY",
    PDRP: "N",
    TERRITORY: "SAN FRANCISCO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "STANFORD HOSPITAL",
    PARENT_NAME: "STANFORD HOSPITAL",
  },
  {
    HCP_NAME: "ALLISON E HARDIN",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "AURORA CANCER CARE",
    PARENT_NAME: "ADVOCATE AURORA HEALTH",
  },
  {
    HCP_NAME: "KARA LYNN TRLICA",
    PDRP: "Y",
    TERRITORY: "MANHATTAN/NJ",
    REGION: "NORTHEAST",
    CHILD_NAME: "THE MOUNT SINAI HOSPITAL",
    PARENT_NAME: "THE MOUNT SINAI HOSPITAL",
  },
  {
    HCP_NAME: "AARON TYLER JONES",
    PDRP: "N",
    TERRITORY: "ATLANTA, GA",
    REGION: "SOUTHEAST",
    CHILD_NAME: "WINSHIP CANCER INSTITUTE PHARMACY-ST",
    PARENT_NAME: "WINSHIP CANCER INSTITUTE PHARMACY-ST",
  },
  {
    HCP_NAME: "SIDNEY MORRIS STOLL",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "LACN-NEW VALLEY PRESBYTERIAN #2",
    PARENT_NAME: "LACN-NEW VALLEY PRESBYTERIAN #2",
  },
  {
    HCP_NAME: "JOSHUA HARRIS",
    PDRP: "N",
    TERRITORY: "BROOKLYN/LONG ISLAND",
    REGION: "NORTHEAST",
    CHILD_NAME: "THE BLAVATNIK FAMILY-CHELSEA MEDICAL CENTER AT MOUNT SINAI",
    PARENT_NAME: "THE BLAVATNIK FAMILY-CHELSEA MEDICAL CENTER AT MOUNT SINAI",
  },
  {
    HCP_NAME: "AMY SIMPSON BROOKS",
    PDRP: "NULL",
    TERRITORY: "ATLANTA, GA",
    REGION: "SOUTHEAST",
    CHILD_NAME: "HARBIN CLINIC MEDICAL ONCOLOGY ROME",
    PARENT_NAME: "HARBIN CLINIC MEDICAL ONCOLOGY ROME",
  },
  {
    HCP_NAME: "CELINA SU-PING ANG",
    PDRP: "N",
    TERRITORY: "MANHATTAN/NJ",
    REGION: "NORTHEAST",
    CHILD_NAME: "THE MOUNT SINAI HOSPITAL",
    PARENT_NAME: "THE MOUNT SINAI HOSPITAL",
  },
  {
    HCP_NAME: "KAREN B PLEWE",
    PDRP: "NULL",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "CANCER TREATMENT CENTERS OF AMERICA CHICAGO",
    PARENT_NAME: "CANCER TREATMENT CENTERS OF AMERICA CHICAGO",
  },
  {
    HCP_NAME: "MARGARET A ROGERS",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "OSF SAINT ANTHONY MEDICAL CENTER",
    PARENT_NAME: "OSF SAINT ANTHONY MEDICAL CENTER",
  },
  {
    HCP_NAME: "MARIAN TENTLER",
    PDRP: "N",
    TERRITORY: "DES MOINES, IA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "NORTHWESTERN MEDICAL FACULTY FOUNDATION RADIOLOGY",
    PARENT_NAME: "NORTHWESTERN MEDICAL FACULTY FOUNDATION RADIOLOGY",
  },
  {
    HCP_NAME: "JORDAN DIANA ROBINSON",
    PDRP: "N",
    TERRITORY: "CHARLOTTE, NC",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "NOVANT HEALTH ONCOLOGY SPECIALISTS-KERNERSVILLE",
    PARENT_NAME: "NOVANT HEALTH CANCER INSTITUTE-FORSYTH (SYMPTOM MANAGEMENT)",
  },
  {
    HCP_NAME: "STACEY P CADOGAN",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "IU HEALTH BALL MEMORIAL CANCER CENTER",
    PARENT_NAME: "IU HEALTH SIMON CANCER CENTER",
  },
  {
    HCP_NAME: "RAZMIG V BABIKIAN",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "CITY OF HOPE COMPREHENSIVE CANCER CENTER-DUARTE",
    PARENT_NAME: "CITY OF HOPE COMPREHENSIVE CANCER CENTER-DUARTE",
  },
  {
    HCP_NAME: "ANGELA SAVERIMUTHU",
    PDRP: "N",
    TERRITORY: "SAN DIEGO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "YUMA REGIONAL MEDICAL CENTER",
    PARENT_NAME: "YUMA REGIONAL MEDICAL CENTER",
  },
  {
    HCP_NAME: "KATHRYN ELIZABETH MASON",
    PDRP: "N",
    TERRITORY: "HARTFORD, CT",
    REGION: "NORTHEAST",
    CHILD_NAME: "YALE-NEW HAVEN HOSPITAL",
    PARENT_NAME: "YALE-NEW HAVEN HOSPITAL",
  },
  {
    HCP_NAME: "KRISTINA GOUTSOULIAK",
    PDRP: "N",
    TERRITORY: "DENVER, CO",
    REGION: "SOUTHWEST",
    CHILD_NAME: "GRAND VALLEY ONCOLOGY",
    PARENT_NAME: "GRAND VALLEY ONCOLOGY",
  },
  {
    HCP_NAME: "JULIE ANN MUSSELL",
    PDRP: "N",
    TERRITORY: "SYRACUSE, NY",
    REGION: "NORTHEAST",
    CHILD_NAME: "ROSWELL PARK CANCER INSTITUTE DEPARTMENT OF U",
    PARENT_NAME: "ROSWELL PARK CANCER INSTITUTE DEPARTMENT OF U",
  },
  {
    HCP_NAME: "JINI HYUN",
    PDRP: "Y",
    TERRITORY: "BROOKLYN/LONG ISLAND",
    REGION: "NORTHEAST",
    CHILD_NAME: "NEW YORK AND PRESBYTERIAN HOSPITAL",
    PARENT_NAME: "NEW YORK AND PRESBYTERIAN HOSPITAL",
  },
  {
    HCP_NAME: "MARWAN MOUNAYAR",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "INDIANA UNIVERSITY HEALTH BALL MEMORIAL HOSPITAL",
    PARENT_NAME: "IU HEALTH SIMON CANCER CENTER",
  },
  {
    HCP_NAME: "ALEXANDRA ARTEAGA",
    PDRP: "N",
    TERRITORY: "MANHATTAN/NJ",
    REGION: "NORTHEAST",
    CHILD_NAME: "NEW YORK AND PRESBYTERIAN HOSPITAL",
    PARENT_NAME: "NEW YORK AND PRESBYTERIAN HOSPITAL",
  },
  {
    HCP_NAME: "ANTONIO GIORDANO",
    PDRP: "N",
    TERRITORY: "BOSTON, MA",
    REGION: "NORTHEAST",
    CHILD_NAME: "DANA FARBER CANCER CENTER",
    PARENT_NAME: "DANA FARBER CANCER CENTER",
  },
  {
    HCP_NAME: "BRITTANI JEAN THOMAS",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "HENRY FORD HOSPITAL",
    PARENT_NAME: "HENRY FORD HOSPITAL",
  },
  {
    HCP_NAME: "MICHELLE R FROH",
    PDRP: "N",
    TERRITORY: "SEATTLE, WA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "KADLEC CLINIC HEMATOLOGY AND ONCOLOGY",
    PARENT_NAME: "KADLEC CLINIC HEMATOLOGY AND ONCOLOGY",
  },
  {
    HCP_NAME: "JENNIFER ELIZABETH SCHIFF",
    PDRP: "N",
    TERRITORY: "BROOKLYN/LONG ISLAND",
    REGION: "NORTHEAST",
    CHILD_NAME: "NEW YORK AND PRESBYTERIAN HOSPITAL",
    PARENT_NAME: "NEW YORK AND PRESBYTERIAN HOSPITAL",
  },
  {
    HCP_NAME: "SANDRA SUE STAEHLER",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "COMMUNITY HOSPITAL ONCOLOGY PHYSICIANS",
    PARENT_NAME: "COMMUNITY HOSPITAL ONCOLOGY PHYSICIANS",
  },
  {
    HCP_NAME: "JAMIE WIGGINS CRAIG",
    PDRP: "NULL",
    TERRITORY: "CHARLESTON, SC",
    REGION: "SOUTHEAST",
    CHILD_NAME: "MCLEOD ONCOLOGY AND HEMATOLOGY SEACOAST",
    PARENT_NAME: "MCLEOD ONCOLOGY AND HEMATOLOGY ASSOCIATES",
  },
  {
    HCP_NAME: "EDWIN CHIU",
    PDRP: "N",
    TERRITORY: "BROOKLYN/LONG ISLAND",
    REGION: "NORTHEAST",
    CHILD_NAME: "NYC HEALTH + HOSPITALS KINGS COUNTY",
    PARENT_NAME: "NYC HEALTH + HOSPITALS KINGS COUNTY",
  },
  {
    HCP_NAME: "GABRIELLE LYNN MONIT D'AMORE",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "MICHIGAN HEALTHCARE PROFESSIONALS",
    PARENT_NAME: "MICHIGAN HEALTHCARE PROFESSIONALS",
  },
  {
    HCP_NAME: "DIEGO FELIPE CABRERA FERNANDEZ",
    PDRP: "Y",
    TERRITORY: "LOUISVILLE, KY",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "THE MEDICAL CENTER AT BOWLING GREEN",
    PARENT_NAME: "THE MEDICAL CENTER AT BOWLING GREEN",
  },
  {
    HCP_NAME: "ALICE MARGARET FOLEY",
    PDRP: "N",
    TERRITORY: "SAN FRANCISCO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "CENTRAL COAST ONCOLOGY AND HEMATOLOGY",
    PARENT_NAME: "CENTRAL COAST ONCOLOGY AND HEMATOLOGY",
  },
  {
    HCP_NAME: "OTTO METZGER",
    PDRP: "N",
    TERRITORY: "BOSTON, MA",
    REGION: "NORTHEAST",
    CHILD_NAME: "DANA FARBER CANCER CENTER",
    PARENT_NAME: "DANA FARBER CANCER CENTER",
  },
  {
    HCP_NAME: "EMILY KATHERINE YOUNG",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
    PARENT_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
  },
  {
    HCP_NAME: "CHELSEA NICOLE THOMAS",
    PDRP: "N",
    TERRITORY: "OKLAHOMA CITY, OK",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "SAINT FRANCIS CANCER CENTER",
    PARENT_NAME: "SAINT FRANCIS CANCER CENTER",
  },
  {
    HCP_NAME: "SISSY A HINOJOS",
    PDRP: "N",
    TERRITORY: "DALLAS, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "TEXAS ONCOLOGY PHARMACY-ODESSA",
    PARENT_NAME: "TEXAS ONCOLOGY BAYLOR SAMMONS CENTER BONE MARROW TRANSPLANT",
  },
  {
    HCP_NAME: "JENNIFER LYNN GILDEN",
    PDRP: "N",
    TERRITORY: "SAN DIEGO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "THE ONCOLOGY INSTITUTE CERRITOS-CORPORATE OFFICE",
    PARENT_NAME: "THE ONCOLOGY INSTITUTE OF HOPE AND INNOVATION ADMIN OFFICE",
  },
  {
    HCP_NAME: "SARA K PASTMAN",
    PDRP: "N",
    TERRITORY: "TAMPA, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME:
      "FLORIDA CANCER SPECIALISTS AND RESEARCH INSTITUTE-ST PETERSBURG",
    PARENT_NAME: "FLORIDA CANCER SPECIALISTS ST PETERSBURG ST ANTHONYS",
  },
  {
    HCP_NAME: "MEGAN L OSBORNE",
    PDRP: "N",
    TERRITORY: "CHARLESTON, SC",
    REGION: "SOUTHEAST",
    CHILD_NAME: "GEORGIA CANCER SPECIALISTS-MACON COLISEUM",
    PARENT_NAME: "NORTHSIDE HOSPITAL INC",
  },
  {
    HCP_NAME: "SARAH E JAX",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "PARK NICOLLET FRAUENSHUH CANCER CENTER",
    PARENT_NAME: "PARK NICOLLET FRAUENSHUH CANCER CENTER",
  },
  {
    HCP_NAME: "CORIN ELG JAYNES",
    PDRP: "N",
    TERRITORY: "CHARLESTON, SC",
    REGION: "SOUTHEAST",
    CHILD_NAME: "CHARLESTON ONCOLOGY",
    PARENT_NAME: "CHARLESTON ONCOLOGY",
  },
  {
    HCP_NAME: "LARISA ANN GALLO",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "CEDARS SINAI COMPREHENSIVE CANCER CENTER PHARMACY",
    PARENT_NAME: "CEDARS SINAI COMPREHENSIVE CANCER CENTER PHARMACY",
  },
  {
    HCP_NAME: "JAMIE LYN CARROLL",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "MAYO CLINIC HEALTH SYSTEM",
    PARENT_NAME: "MAYO CLINIC HEALTH SYSTEM",
  },
  {
    HCP_NAME: "NATALIE A AKKERMAN",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME:
      "M HEALTH FAIRVIEW UNIVERSITY OF MINNESOTA MEDICAL CENTER-WEST BANK HOSPITAL",
    PARENT_NAME:
      "M HEALTH FAIRVIEW UNIVERSITY OF MINNESOTA MEDICAL CENTER-WEST BANK HOSPITAL",
  },
  {
    HCP_NAME: "SOFIA PALACIO CARDENAS",
    PDRP: "N",
    TERRITORY: "PHOENIX, AZ",
    REGION: "SOUTHWEST",
    CHILD_NAME: "NEW MEXICO CANCER CENTER ALBUQUERQUE",
    PARENT_NAME: "NEW MEXICO CANCER CENTER ALBUQUERQUE",
  },
  {
    HCP_NAME: "KELLY RACHEL GRAFMAN",
    PDRP: "NULL",
    TERRITORY: "PHOENIX, AZ",
    REGION: "SOUTHWEST",
    CHILD_NAME: "IRONWOOD CANCER AND RESEARCH CENTERS-CHANDLER 1",
    PARENT_NAME: "IRONWOOD CANCER AND RESEARCH CENTER-CHANDLER II",
  },
  {
    HCP_NAME: "AIXA E SOYANO MULLER",
    PDRP: "Y",
    TERRITORY: "TAMPA, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME:
      "H LEE MOFFITT CANCER CENTER RICHARD SCHULZE OUTPATIENT CENTER MCKINLEY CAMPUS",
    PARENT_NAME:
      "H LEE MOFFITT CANCER CENTER RICHARD SCHULZE OUTPATIENT CENTER MCKINLEY CAMPUS",
  },
  {
    HCP_NAME: "MUHAMMAD U USMAN",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "ASCENSION BORGESS CANCER CENTER",
    PARENT_NAME: "ASCENSION BORGESS CANCER CENTER",
  },
  {
    HCP_NAME: "NIKOLE L SLOWICK DELAIR",
    PDRP: "N",
    TERRITORY: "SYRACUSE, NY",
    REGION: "NORTHEAST",
    CHILD_NAME: "C R WOOD CANCER CENTER",
    PARENT_NAME: "C R WOOD CANCER CENTER",
  },
  {
    HCP_NAME: "JESSICA KAY SCHRECK",
    PDRP: "N",
    TERRITORY: "PHOENIX, AZ",
    REGION: "SOUTHWEST",
    CHILD_NAME: "AO-WILMOT OFFICE-ORALS",
    PARENT_NAME: "AO-WILMOT OFFICE-ORALS",
  },
  {
    HCP_NAME: "SRIJANA RAI",
    PDRP: "N",
    TERRITORY: "SEATTLE, WA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "CANCER CARE NORTHWEST-SOUTH SPOKANE",
    PARENT_NAME: "CANCER CARE NORTHWEST-SOUTH SPOKANE",
  },
  {
    HCP_NAME: "NATASHA GARG",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "CITY OF HOPE COMPREHENSIVE CANCER CENTER-DUARTE",
    PARENT_NAME: "CITY OF HOPE COMPREHENSIVE CANCER CENTER-DUARTE",
  },
  {
    HCP_NAME: "KRISHNA PRASAD KOLANDAIVEL",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "ESSENTIA HEALTH ST JOSEPHS CANCER CENTER BRAINERD",
    PARENT_NAME: "ESSENTIA HEALTH SPECIALTY PHARMACY",
  },
  {
    HCP_NAME: "SIERRA LEE ROBERTS",
    PDRP: "NULL",
    TERRITORY: "CLEVELAND, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "CONEMAUGH CANCER CARE CENTER",
    PARENT_NAME: "CONEMAUGH CANCER CARE CENTER",
  },
  {
    HCP_NAME: "SAMIR MAZHARUDDIN",
    PDRP: "N",
    TERRITORY: "HOUSTON, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "MEMORIAL HERMANN-TEXAS MEDICAL CENTER",
    PARENT_NAME: "MEMORIAL HERMANN-TEXAS MEDICAL CENTER",
  },
  {
    HCP_NAME: "JEREMY AARON ROSS",
    PDRP: "N",
    TERRITORY: "DALLAS, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "MD ANDERSON CANCER CENTER NETWORK THE UNIVERSITY OF TEXAS",
    PARENT_NAME: "MD ANDERSON CANCER CENTER NETWORK THE UNIVERSITY OF TEXAS",
  },
  {
    HCP_NAME: "AENA PATEL",
    PDRP: "N",
    TERRITORY: "DALLAS, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME:
      "THE CENTER FOR CANCER AND BLOOD DISORDERS BUSINESS ADMINISTRATION OFFICE",
    PARENT_NAME:
      "THE CENTER FOR CANCER AND BLOOD DISORDERS BUSINESS ADMINISTRATION OFFICE",
  },
  {
    HCP_NAME: "SCOTT BRANDON MCCORD",
    PDRP: "N",
    TERRITORY: "DALLAS, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "TEXAS ONCOLOGY KELLER",
    PARENT_NAME: "TEXAS ONCOLOGY BAYLOR SAMMONS CENTER BONE MARROW TRANSPLANT",
  },
  {
    HCP_NAME: "DAVID JARED KOBULNICKY",
    PDRP: "Y",
    TERRITORY: "RICHMOND, VA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "VIRGINIA ONCOLOGY ASSOCIATES HAMPTON CAREPLEX",
    PARENT_NAME: "VIRGINIA ONCOLOGY ASSOCIATES (BROCK CANCER CENTER)",
  },
  {
    HCP_NAME: "TYLER WILLIAM SNEDDEN",
    PDRP: "N",
    TERRITORY: "SAN ANTONIO, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "TEXAS ONCOLOGY WACO",
    PARENT_NAME: "TEXAS ONCOLOGY BAYLOR SAMMONS CENTER BONE MARROW TRANSPLANT",
  },
  {
    HCP_NAME: "NAVEED R CHEEMA",
    PDRP: "N",
    TERRITORY: "DALLAS, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "TEXAS ONCOLOGY MESQUITE",
    PARENT_NAME: "TEXAS ONCOLOGY BAYLOR SAMMONS CENTER BONE MARROW TRANSPLANT",
  },
  {
    HCP_NAME: "AMY ELIZABETH MCGHEE-JEZ",
    PDRP: "N",
    TERRITORY: "PHILADELPHIA, PA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "MEDICAL ONCOLOGY HEMATOLOGY CONSULTANTS PA",
    PARENT_NAME: "MEDICAL ONCOLOGY HEMATOLOGY CONSULTANTS PA",
  },
  {
    HCP_NAME: "SHRUTI SINGH",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "NORTHWEST CANCER CENTER",
    PARENT_NAME: "NORTHWEST CANCER CENTER",
  },
  {
    HCP_NAME: "ROBERTO STEFAN FRATAMICO",
    PDRP: "N",
    TERRITORY: "PHILADELPHIA, PA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "LEHIGH VALLEY HOSPITAL-CEDAR CREST",
    PARENT_NAME: "LEHIGH VALLEY HOSPITAL-CEDAR CREST",
  },
  {
    HCP_NAME: "ERIN D CHAMBERLAIN",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
    PARENT_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
  },
  {
    HCP_NAME: "KATHRYN A BAXSTROM",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "REGIONS HOSPITAL",
    PARENT_NAME: "REGIONS HOSPITAL",
  },
  {
    HCP_NAME: "YANG LIU",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "MINNESOTA ONCOLOGY HEMATOLOGY PA",
    PARENT_NAME: "MINNESOTA ONCOLOGY HEMATOLOGY PA",
  },
  {
    HCP_NAME: "POORNI MANCHUREKHA MANOHAR",
    PDRP: "N",
    TERRITORY: "SEATTLE, WA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "SEATTLE CANCER CARE ALLIANCE SCCA AT UW MEDICAL CENTER",
    PARENT_NAME: "SEATTLE CANCER CARE ALLIANCE",
  },
  {
    HCP_NAME: "NICHOLAS TYLER GORDEN",
    PDRP: "Y",
    TERRITORY: "BEND, OR",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "SAINT ALPHONSUS REGIONAL MEDICAL CENTER",
    PARENT_NAME: "SAINT ALPHONSUS REGIONAL MEDICAL CENTER",
  },
  {
    HCP_NAME: "JAMES MICHAEL MARTIN",
    PDRP: "N",
    TERRITORY: "CLEVELAND, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "UNIVERSITY HOSPITALS CLEVELAND MEDICAL CENTER",
    PARENT_NAME: "UNIVERSITY HOSPITALS CLEVELAND MEDICAL CENTER",
  },
  {
    HCP_NAME: "JENNIFER A FAIG",
    PDRP: "N",
    TERRITORY: "BOSTON, MA",
    REGION: "NORTHEAST",
    CHILD_NAME: "DANA FARBER CANCER CENTER",
    PARENT_NAME: "DANA FARBER CANCER CENTER",
  },
  {
    HCP_NAME: "VICTORIA T RIZK",
    PDRP: "N",
    TERRITORY: "TAMPA, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME: "MSKCC IMAGING CENTER MRI",
    PARENT_NAME: "MSKCC IMAGING CENTER MRI",
  },
  {
    HCP_NAME: "DANIEL ZEE-WEI WU",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "KAISER PERMANENTE SOUTH SAN FRANCISCO",
    PARENT_NAME: "KAISER PERMANENTE SOUTH SAN FRANCISCO",
  },
  {
    HCP_NAME: "ERIC M BANK",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "RIDLEY-TREE CANCER CENTER",
    PARENT_NAME: "RIDLEY-TREE CANCER CENTER",
  },
  {
    HCP_NAME: "ROBA S ALHASAN",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "MCLAREN GREATER LANSING",
    PARENT_NAME: "KARMANOS CANCER INSTITUTE",
  },
  {
    HCP_NAME: "ROHIT VENKATESAN",
    PDRP: "N",
    TERRITORY: "HOUSTON, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "UTMB HEALTH ORTHOPEDICS LEAGUE CITY CAMPUS",
    PARENT_NAME: "UTMB HEALTH ORTHOPEDICS LEAGUE CITY CAMPUS",
  },
  {
    HCP_NAME: "JASLEEN K KHANUJA",
    PDRP: "N",
    TERRITORY: "PHOENIX, AZ",
    REGION: "SOUTHWEST",
    CHILD_NAME: "IRONWOOD CANCER AND RESEARCH CENTERS-CHANDLER 1",
    PARENT_NAME: "IRONWOOD CANCER AND RESEARCH CENTER-CHANDLER II",
  },
  {
    HCP_NAME: "DAVID M MACARI",
    PDRP: "Y",
    TERRITORY: "COLUMBUS, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "PROMEDICA HEMATOLOGY ONCOLOGY ASSOCIATES",
    PARENT_NAME: "PROMEDICA HEMATOLOGY ONCOLOGY ASSOCIATES",
  },
  {
    HCP_NAME: "K'ANNE CASH ARTHUR",
    PDRP: "N",
    TERRITORY: "OKLAHOMA CITY, OK",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "HIGHLANDS ONCOLOGY GROUP FAYETTEVILLE",
    PARENT_NAME: "HIGHLANDS ONCOLOGY GROUP FAYETTEVILLE",
  },
  {
    HCP_NAME: "EMILY ANNE NAGLER",
    PDRP: "N",
    TERRITORY: "SAN DIEGO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SCRIPPS GREEN CANCER CENTER",
    PARENT_NAME: "SCRIPPS GREEN CANCER CENTER",
  },
  {
    HCP_NAME: "ELIZABETH JANE CATHCART-RAKE",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "MAYO CLINIC",
    PARENT_NAME: "MAYO CLINIC HEALTH SYSTEM",
  },
  {
    HCP_NAME: "EUGENE MITCHELL LONG",
    PDRP: "N",
    TERRITORY: "CHARLESTON, SC",
    REGION: "SOUTHEAST",
    CHILD_NAME: "AUGUSTA ONCOLOGY ASSOCIATES PC",
    PARENT_NAME: "AUGUSTA ONCOLOGY ASSOCIATES PC",
  },
  {
    HCP_NAME: "FARAH EDITH NASRATY",
    PDRP: "N",
    TERRITORY: "SAN DIEGO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SCRIPPS GREEN CANCER CENTER",
    PARENT_NAME: "SCRIPPS GREEN CANCER CENTER",
  },
  {
    HCP_NAME: "DIANA SARAVIA",
    PDRP: "N",
    TERRITORY: "WEST PALM BEACH, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME:
      "CLEVELAND CLINIC FLORIDA WESTON HEMATOLOGY AND BLOOD DISORDERS",
    PARENT_NAME: "CLEVELAND CLINIC FOUNDATION",
  },
  {
    HCP_NAME: "SAMUEL S LEE",
    PDRP: "N",
    TERRITORY: "RICHMOND, VA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "VIRGINIA CANCER SPECIALISTS FAIRFAX",
    PARENT_NAME: "VIRGINIA CANCER SPECIALISTS FAIRFAX",
  },
  {
    HCP_NAME: "SONIA CHRISTIAN",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "IL CANCER SPECIALISTS NILES OFFICE",
    PARENT_NAME: "IL CANCER SPECIALISTS NILES OFFICE",
  },
  {
    HCP_NAME: "LI LI",
    PDRP: "N",
    TERRITORY: "SAN FRANCISCO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SANTA CLARA VALLEY MEDICAL",
    PARENT_NAME: "SANTA CLARA VALLEY MEDICAL",
  },
  {
    HCP_NAME: "KIN WAI HUNG",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
    PARENT_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
  },
  {
    HCP_NAME: "GREGORY A GILMORE",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "THE ONCOLOGY INSTITUTE CERRITOS-CORPORATE OFFICE",
    PARENT_NAME: "THE ONCOLOGY INSTITUTE OF HOPE AND INNOVATION ADMIN OFFICE",
  },
  {
    HCP_NAME: "ERIC WIRTSCHAFTER",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
    PARENT_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
  },
  {
    HCP_NAME: "SARAH ELIZABETH TOMASSETTI",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
    PARENT_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
  },
  {
    HCP_NAME: "MELISSA ANN NARDI",
    PDRP: "N",
    TERRITORY: "SAN DIEGO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SCRIPPS GREEN CANCER CENTER",
    PARENT_NAME: "SCRIPPS GREEN CANCER CENTER",
  },
  {
    HCP_NAME: "HEIDI MARIA EGLOFF",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "HENRY FORD HOSPITAL",
    PARENT_NAME: "HENRY FORD HOSPITAL",
  },
  {
    HCP_NAME: "KIMBERLY P KU",
    PDRP: "N",
    TERRITORY: "DES MOINES, IA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "ILLINOIS CANCER CARE PEORIA",
    PARENT_NAME: "ILLINOIS CANCER CARE PEORIA",
  },
  {
    HCP_NAME: "LEANDRO P MORAES",
    PDRP: "N",
    TERRITORY: "TAMPA, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME: "ONCOLOGY HEMATOLOGY OF LOUDOUN AND RESTON-LANSDOWNE",
    PARENT_NAME: "ONCOLOGY HEMATOLOGY OF LOUDOUN AND RESTON-LANSDOWNE",
  },
  {
    HCP_NAME: "SHAWN PETERSON",
    PDRP: "N",
    TERRITORY: "LOUISVILLE, KY",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "BAPTIST HEALTH LEXINGTON",
    PARENT_NAME: "BAPTIST HEALTH LEXINGTON",
  },
  {
    HCP_NAME: "HADEER JOSEPH MICHAEL",
    PDRP: "NULL",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME:
      "OAKLAND MEDICAL GROUP FARMINGTON HILLS CANCER CENTER DIVISION OF MICHIGAN HEALTHCARE PROFESSIONAL",
    PARENT_NAME: "MICHIGAN HEALTHCARE PROFESSIONALS",
  },
  {
    HCP_NAME: "ANDREW DUY PHAM",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "BEVERLY HILLS CANCER CENTER",
    PARENT_NAME: "BEVERLY HILLS CANCER CENTER",
  },
  {
    HCP_NAME: "MATTHEW BLAKE LOCKWOOD",
    PDRP: "N",
    TERRITORY: "OKLAHOMA CITY, OK",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "HIGHLANDS ONCOLOGY GROUP FAYETTEVILLE",
    PARENT_NAME: "HIGHLANDS ONCOLOGY GROUP FAYETTEVILLE",
  },
  {
    HCP_NAME: "ROBERT STEVEN FOLK",
    PDRP: "NULL",
    TERRITORY: "CLEVELAND, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "UNIVERSITY HOSPITALS CLEVELAND MEDICAL CENTER",
    PARENT_NAME: "UNIVERSITY HOSPITALS CLEVELAND MEDICAL CENTER",
  },
  {
    HCP_NAME: "CARRIE LEIS FLIPPEN",
    PDRP: "NULL",
    TERRITORY: "CHARLESTON, SC",
    REGION: "SOUTHEAST",
    CHILD_NAME: "MUSC HEALTH",
    PARENT_NAME: "MUSC HEALTH",
  },
  {
    HCP_NAME: "LAUREN OPPENHEIMER CURRAN",
    PDRP: "N",
    TERRITORY: "SYRACUSE, NY",
    REGION: "NORTHEAST",
    CHILD_NAME: "RADIATION ONCOLOGY OF ROCHESTER; PLLC",
    PARENT_NAME: "RADIATION ONCOLOGY OF ROCHESTER; PLLC",
  },
  {
    HCP_NAME: "LEANN M BLANKENSHIP",
    PDRP: "N",
    TERRITORY: "SAN FRANCISCO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME:
      "OAKLAND MEDICAL GROUP FARMINGTON HILLS CANCER CENTER DIVISION OF MICHIGAN HEALTHCARE PROFESSIONAL",
    PARENT_NAME: "MICHIGAN HEALTHCARE PROFESSIONALS",
  },
  {
    HCP_NAME: "LACI D LITTLE",
    PDRP: "N",
    TERRITORY: "SEATTLE, WA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "BILLINGS CLINIC CANCER CENTER",
    PARENT_NAME: "BILLINGS CLINIC",
  },
  {
    HCP_NAME: "XIN LI",
    PDRP: "N",
    TERRITORY: "SAN FRANCISCO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "ALTA BATES COMPREHENSIVE CANCER CENTER",
    PARENT_NAME: "ALTA BATES COMPREHENSIVE CANCER CENTER",
  },
  {
    HCP_NAME: "MARK D FLOYD",
    PDRP: "N",
    TERRITORY: "SAN ANTONIO, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "CANCER CLINIC",
    PARENT_NAME: "CANCER CLINIC",
  },
  {
    HCP_NAME: "CIARA CATHERINE O'SULLIVAN",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "MAYO CLINIC HEALTH SYSTEM",
    PARENT_NAME: "MAYO CLINIC HEALTH SYSTEM",
  },
  {
    HCP_NAME: "JULIA P BROCKWAY-MARCHELLO",
    PDRP: "N",
    TERRITORY: "BROOKLYN/LONG ISLAND",
    REGION: "NORTHEAST",
    CHILD_NAME: "MSKCC IMAGING CENTER MRI",
    PARENT_NAME: "MSKCC IMAGING CENTER MRI",
  },
  {
    HCP_NAME: "GURLEEN PASRICHA",
    PDRP: "N",
    TERRITORY: "CLEVELAND, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "ALLEGHENY GENERAL HOSPITAL",
    PARENT_NAME: "ALLEGHENY GENERAL HOSPITAL",
  },
  {
    HCP_NAME: "SAMI M ALI",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "HEM ONC SPECIALISTS - ORALS",
    PARENT_NAME: "HEM ONC SPECIALISTS - ORALS",
  },
  {
    HCP_NAME: "MAKARDHWAJ SARVADAMAN SHRIVASTAVA",
    PDRP: "Y",
    TERRITORY: "PHOENIX, AZ",
    REGION: "SOUTHWEST",
    CHILD_NAME: "YUMA REGIONAL MEDICAL CENTER",
    PARENT_NAME: "YUMA REGIONAL MEDICAL CENTER",
  },
  {
    HCP_NAME: "JESSICA LYNN BUTTERFIELD",
    PDRP: "N",
    TERRITORY: "BEND, OR",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "SAINT ALPHONSUS REGIONAL MEDICAL CENTER",
    PARENT_NAME: "SAINT ALPHONSUS REGIONAL MEDICAL CENTER",
  },
  {
    HCP_NAME: "DONIELLE F SLIWA",
    PDRP: "N",
    TERRITORY: "BOSTON, MA",
    REGION: "NORTHEAST",
    CHILD_NAME: "UNIVERSITY OF VERMONT MEDICAL CENTER",
    PARENT_NAME: "UNIVERSITY OF VERMONT MEDICAL CENTER",
  },
  {
    HCP_NAME: "JEFFREY M FLOYD",
    PDRP: "NULL",
    TERRITORY: "CHARLESTON, SC",
    REGION: "SOUTHEAST",
    CHILD_NAME: "CHARLESTON ONCOLOGY",
    PARENT_NAME: "CHARLESTON ONCOLOGY",
  },
  {
    HCP_NAME: "ALLISON L HAWKINS",
    PDRP: "N",
    TERRITORY: "ORLANDO, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME: "FLORIDA CANCER SPECIALISTS ORLANDO ORANGE",
    PARENT_NAME: "FLORIDA CANCER SPECIALISTS ORLANDO ORANGE",
  },
  {
    HCP_NAME: "COURTNEY KAE ANDERSON",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "CANCER TREATMENT CENTERS OF AMERICA CHICAGO",
    PARENT_NAME: "CANCER TREATMENT CENTERS OF AMERICA CHICAGO",
  },
  {
    HCP_NAME: "DAVID D SHIN",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
    PARENT_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
  },
  {
    HCP_NAME: "GEORGIOS CONSTANTINOU",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "OCHSNER MEDICAL CENTER",
    PARENT_NAME: "OCHSNER MEDICAL CENTER",
  },
  {
    HCP_NAME: "RAHUL GOSAIN",
    PDRP: "N",
    TERRITORY: "SYRACUSE, NY",
    REGION: "NORTHEAST",
    CHILD_NAME: "GUTHRIE ROBERT PACKER HOSPITAL",
    PARENT_NAME: "GUTHRIE ROBERT PACKER HOSPITAL",
  },
  {
    HCP_NAME: "AHMED MUHAMMAD EZAT ELKHANANY",
    PDRP: "N",
    TERRITORY: "BIRMINGHAM, AL",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "UNIVERSITY OF ALABAMA HOSPITAL",
    PARENT_NAME: "THE KIRKLIN CLINIC OF UAB HOSPITAL",
  },
  {
    HCP_NAME: "MARIA RAQUEL NUNES",
    PDRP: "N",
    TERRITORY: "BALTIMORE, MD",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "SIBLEY MEMORIAL HOSPITAL",
    PARENT_NAME: "SIBLEY MEMORIAL HOSPITAL",
  },
  {
    HCP_NAME: "JULIAN R DAVIS",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
    PARENT_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
  },
  {
    HCP_NAME: "BHARGAVI PULLURI",
    PDRP: "N",
    TERRITORY: "BALTIMORE, MD",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "ST AGNES CANCER CENTER",
    PARENT_NAME: "ASCENSION SAINT AGNES HOSPITAL",
  },
  {
    HCP_NAME: "THOMAS CHRISTIAN WEART",
    PDRP: "N",
    TERRITORY: "RICHMOND, VA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "VIRGINIA CANCER INSTITUTE SARAH CANNON CANCER INSTITUTE",
    PARENT_NAME: "VIRGINIA CANCER INSTITUTE WEST END",
  },
  {
    HCP_NAME: "NORA ROSE SUDARSAN",
    PDRP: "N",
    TERRITORY: "BALTIMORE, MD",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "MEDSTAR GEORGETOWN UNIVERSITY HOSPITAL",
    PARENT_NAME: "MEDSTAR GEORGETOWN UNIVERSITY HOSPITAL",
  },
  {
    HCP_NAME: "URMEEL HASMUKH PATEL",
    PDRP: "N",
    TERRITORY: "HOUSTON, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "MILLENNIUM PHYSICIANS KINGWOOD-ONCOLOGY AND RHEUMATOLOGY",
    PARENT_NAME: "MILLENNIUM PHYSICIANS KINGWOOD-ONCOLOGY AND RHEUMATOLOGY",
  },
  {
    HCP_NAME: "SAMEER TOLAY",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "SSM HEALTH MEDICATION PURCHASING",
    PARENT_NAME: "SSM HEALTH MEDICATION PURCHASING",
  },
  {
    HCP_NAME: "LINDA PHUONG HOANG",
    PDRP: "N",
    TERRITORY: "SAN FRANCISCO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "DIGNITY HEALTH MERCY ONCOLOGY CENTER PHA",
    PARENT_NAME: "DIGNITY HEALTH MERCY ONCOLOGY CENTER PHA",
  },
  {
    HCP_NAME: "VAIA FLOROU",
    PDRP: "N",
    TERRITORY: "DENVER, CO",
    REGION: "SOUTHWEST",
    CHILD_NAME: "HUNTSMAN CANCER HOSPITAL",
    PARENT_NAME: "HUNTSMAN CANCER HOSPITAL",
  },
  {
    HCP_NAME: "PEGGY ANN SANCHEZ",
    PDRP: "NULL",
    TERRITORY: "DALLAS, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME:
      "THE CENTER FOR CANCER AND BLOOD DISORDERS BUSINESS ADMINISTRATION OFFICE",
    PARENT_NAME:
      "THE CENTER FOR CANCER AND BLOOD DISORDERS BUSINESS ADMINISTRATION OFFICE",
  },
  {
    HCP_NAME: "JESSICA LAUREN KNAPP",
    PDRP: "N",
    TERRITORY: "MANHATTAN/NJ",
    REGION: "NORTHEAST",
    CHILD_NAME: "THE MOUNT SINAI HOSPITAL",
    PARENT_NAME: "THE MOUNT SINAI HOSPITAL",
  },
  {
    HCP_NAME: "TARA D HENRIKSON",
    PDRP: "N",
    TERRITORY: "DES MOINES, IA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "NORTHWESTERN MEDICAL FACULTY FOUNDATION RADIOLOGY",
    PARENT_NAME: "NORTHWESTERN MEDICAL FACULTY FOUNDATION RADIOLOGY",
  },
  {
    HCP_NAME: "JAYME MARIE ROBERTS",
    PDRP: "N",
    TERRITORY: "COLUMBUS, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "JAMES CARE WOMENS CANCER CENTER",
    PARENT_NAME: "JAMES CARE WOMENS CANCER CENTER",
  },
  {
    HCP_NAME: "JASON J BERGSBAKEN",
    PDRP: "NULL",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "UW HEALTH ACO INC",
    PARENT_NAME: "UW HEALTH ACO INC",
  },
  {
    HCP_NAME: "ERIC M DALLARA",
    PDRP: "NULL",
    TERRITORY: "BOSTON, MA",
    REGION: "NORTHEAST",
    CHILD_NAME: "NEW ENGLAND CANCER SPECIALISTS-SCARBOROUGH",
    PARENT_NAME: "NEW ENGLAND CANCER SPECIALISTS-SCARBOROUGH",
  },
  {
    HCP_NAME: "SURABHI PATHAK",
    PDRP: "N",
    TERRITORY: "LOUISVILLE, KY",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "KINGS DAUGHTERS MEDICAL CENTER",
    PARENT_NAME: "KINGS DAUGHTERS MEDICAL CENTER",
  },
  {
    HCP_NAME: "MATTHEW JAY MARSTON",
    PDRP: "NULL",
    TERRITORY: "BOSTON, MA",
    REGION: "NORTHEAST",
    CHILD_NAME: "NORTHERN LIGHT EMMC LAFAYETTE FAMILY CANCER CARE",
    PARENT_NAME: "NORTHERN LIGHT EMMC LAFAYETTE FAMILY CANCER CARE",
  },
  {
    HCP_NAME: "RAHUL RAVILLA",
    PDRP: "N",
    TERRITORY: "SYRACUSE, NY",
    REGION: "NORTHEAST",
    CHILD_NAME: "NEW YORK ONCOLOGY HEMATOLOGY ALBANY CANCER CENTER",
    PARENT_NAME: "NEW YORK ONCOLOGY HEMATOLOGY ALBANY CANCER CENTER",
  },
  {
    HCP_NAME: "BARBARA JANE RANDALL",
    PDRP: "NULL",
    TERRITORY: "OKLAHOMA CITY, OK",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "SAINT FRANCIS CANCER CENTER",
    PARENT_NAME: "SAINT FRANCIS CANCER CENTER",
  },
  {
    HCP_NAME: "ANDREA LYNN VENTOLA",
    PDRP: "N",
    TERRITORY: "MANHATTAN/NJ",
    REGION: "NORTHEAST",
    CHILD_NAME: "RUTGERS CANCER INSTITUTE OF NEW JERSEY",
    PARENT_NAME: "RUTGERS CANCER INSTITUTE OF NEW JERSEY",
  },
  {
    HCP_NAME: "NOELE M MYERS",
    PDRP: "N",
    TERRITORY: "PHILADELPHIA, PA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "TEMPLE UNIVERSITY HOSPITAL",
    PARENT_NAME: "TEMPLE UNIVERSITY COMPREHENSIVE CANCER CENTER",
  },
  {
    HCP_NAME: "CANDELARIA MCELHINNY",
    PDRP: "N",
    TERRITORY: "SYRACUSE, NY",
    REGION: "NORTHEAST",
    CHILD_NAME: "ROSWELL PARK CANCER INSTITUTE DEPARTMENT OF U",
    PARENT_NAME: "ROSWELL PARK CANCER INSTITUTE DEPARTMENT OF U",
  },
  {
    HCP_NAME: "SHELLEY S MILES",
    PDRP: "N",
    TERRITORY: "DENVER, CO",
    REGION: "SOUTHWEST",
    CHILD_NAME: "COMPREHENSIVE CANCER CENTER-CENTRAL VALLEY",
    PARENT_NAME: "COMPREHENSIVE CANCER CENTER-CENTRAL VALLEY",
  },
  {
    HCP_NAME: "PATIENCE M TERKOWSKI",
    PDRP: "N",
    TERRITORY: "SYRACUSE, NY",
    REGION: "NORTHEAST",
    CHILD_NAME: "POTTSTOWN MEMORIAL REGIONAL CANCER CENTER",
    PARENT_NAME: "POTTSTOWN MEMORIAL REGIONAL CANCER CENTER",
  },
  {
    HCP_NAME: "NICOLE M PRUCHNO",
    PDRP: "N",
    TERRITORY: "DES MOINES, IA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "UNITYPOINT HEALTH-ST LUKES NASSIF RADIATION CENTER",
    PARENT_NAME: "UNITYPOINT HEALTH-ST LUKES NASSIF RADIATION CENTER",
  },
  {
    HCP_NAME: "CHRISTINE MICHELLE DELCIOPPO",
    PDRP: "N",
    TERRITORY: "CHARLESTON, SC",
    REGION: "SOUTHEAST",
    CHILD_NAME: "CHARLESTON ONCOLOGY",
    PARENT_NAME: "CHARLESTON ONCOLOGY",
  },
  {
    HCP_NAME: "HADLEY MUNN SPENCER",
    PDRP: "N",
    TERRITORY: "CHARLOTTE, NC",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "ONCOLOGY SPECIALISTS OF CHARLOTTE-SOUTH CHARLOTTE",
    PARENT_NAME: "ONCOLOGY SPECIALISTS OF CHARLOTTE",
  },
  {
    HCP_NAME: "JENNA D THIBODEAU",
    PDRP: "N",
    TERRITORY: "TAMPA, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME: "FLORIDA CANCER SPECIALISTS FORT MYERS CANCER CENTER",
    PARENT_NAME: "FLORIDA CANCER SPECIALISTS FORT MYERS CANCER CENTER",
  },
  {
    HCP_NAME: "SWEEKRITI ADHIKARI",
    PDRP: "N",
    TERRITORY: "JACKSON, MS",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "OUR LADY OF LOURDES REGIONAL MEDICAL CENTER",
    PARENT_NAME: "OUR LADY OF LOURDES REGIONAL MEDICAL CENTER",
  },
  {
    HCP_NAME: "MUHAMMAD SARFRAZ NAWAZ",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "HEMATOLOGY ONCOLOGY OF INDIANA INDIANAPOLIS",
    PARENT_NAME: "HEMATOLOGY ONCOLOGY OF INDIANA INDIANAPOLIS",
  },
  {
    HCP_NAME: "MUHAMMAD SAAD SAAD KHAN",
    PDRP: "N",
    TERRITORY: "BALTIMORE, MD",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "MEDICAL ONCOLOGY AND HEMATOLOGY AT MERCY",
    PARENT_NAME: "MERCY MEDICAL CENTER",
  },
  {
    HCP_NAME: "DIAA OSMAN",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "MINNESOTA ONCOLOGY HEMATOLOGY PA",
    PARENT_NAME: "MINNESOTA ONCOLOGY HEMATOLOGY PA",
  },
  {
    HCP_NAME: "BO ZHAO",
    PDRP: "N",
    TERRITORY: "RICHMOND, VA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "UNIVERSITY HOSPITALS CLEVELAND MEDICAL CENTER",
    PARENT_NAME: "UNIVERSITY HOSPITALS CLEVELAND MEDICAL CENTER",
  },
  {
    HCP_NAME: "AMANDA M PARKES",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "UW HEALTH ACO INC",
    PARENT_NAME: "UW HEALTH ACO INC",
  },
  {
    HCP_NAME: "PAUL V LETENDRE",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "GUNDERSEN HEALTH SYSTEM LA CROSSE CAMPUS",
    PARENT_NAME: "GUNDERSEN HEALTH SYSTEM LA CROSSE CAMPUS",
  },
  {
    HCP_NAME: "AJAY DHAKAL",
    PDRP: "N",
    TERRITORY: "SYRACUSE, NY",
    REGION: "NORTHEAST",
    CHILD_NAME: "PLUTA CANCER CENTER URMC",
    PARENT_NAME: "PLUTA CANCER CENTER URMC",
  },
  {
    HCP_NAME: "DORIS HANSEN",
    PDRP: "N",
    TERRITORY: "JACKSON, MS",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME:
      "H LEE MOFFITT CANCER CENTER RICHARD SCHULZE OUTPATIENT CENTER MCKINLEY CAMPUS",
    PARENT_NAME:
      "H LEE MOFFITT CANCER CENTER RICHARD SCHULZE OUTPATIENT CENTER MCKINLEY CAMPUS",
  },
  {
    HCP_NAME: "LARA A KUJTAN",
    PDRP: "N",
    TERRITORY: "KANSAS CITY, MO",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "RICHARD AND ANNETTE BLOCH CANCER CENTER AT UNIVERSITY HEALTH",
    PARENT_NAME: "RICHARD AND ANNETTE BLOCH CANCER CENTER AT UNIVERSITY HEALTH",
  },
  {
    HCP_NAME: "SAAD YOUSUF",
    PDRP: "N",
    TERRITORY: "WHITE PLAINS, NY",
    REGION: "NORTHEAST",
    CHILD_NAME: "VASSAR BROTHERS MEDICAL CENTER",
    PARENT_NAME: "VASSAR BROTHERS MEDICAL CENTER",
  },
  {
    HCP_NAME: "KRISSTINA LORRAINE GOWIN",
    PDRP: "N",
    TERRITORY: "PHOENIX, AZ",
    REGION: "SOUTHWEST",
    CHILD_NAME: "BANNER CANCER CENTER SPECIALISTS LLC",
    PARENT_NAME: "BANNER CANCER CENTER SPECIALISTS LLC",
  },
  {
    HCP_NAME: "SHIN YIN LEE",
    PDRP: "N",
    TERRITORY: "SEATTLE, WA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "BILLINGS CLINIC",
    PARENT_NAME: "BILLINGS CLINIC",
  },
  {
    HCP_NAME: "IRENE-NICOLE MITERIA LUCERO",
    PDRP: "N",
    TERRITORY: "SAN DIEGO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SOUTH COUNTY HEMATOLOGY ONCOLOGY",
    PARENT_NAME: "SOUTH COUNTY HEMATOLOGY ONCOLOGY",
  },
  {
    HCP_NAME: "ROHIT R RAO",
    PDRP: "N",
    TERRITORY: "ORLANDO, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME: "MAYO CLINIC HEALTH SYSTEM",
    PARENT_NAME: "MAYO CLINIC HEALTH SYSTEM",
  },
  {
    HCP_NAME: "OLGA B DOLGIKH",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME:
      "OAKLAND MEDICAL GROUP FARMINGTON HILLS CANCER CENTER DIVISION OF MICHIGAN HEALTHCARE PROFESSIONAL",
    PARENT_NAME: "MICHIGAN HEALTHCARE PROFESSIONALS",
  },
  {
    HCP_NAME: "TRACI DAWN MORRISON",
    PDRP: "N",
    TERRITORY: "BIRMINGHAM, AL",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "RADIOLOGY CLINIC LLC AT DCH REGIONAL MEDICAL CENTER",
    PARENT_NAME: "RADIOLOGY CLINIC LLC AT DCH REGIONAL MEDICAL CENTER",
  },
  {
    HCP_NAME: "ROBERTO ANTONIO LEON FERRE",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "MAYO CLINIC HEALTH SYSTEM",
    PARENT_NAME: "MAYO CLINIC HEALTH SYSTEM",
  },
  {
    HCP_NAME: "KENDAL COLUMBIA WEBB",
    PDRP: "N",
    TERRITORY: "SEATTLE, WA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "KATMAI ONCOLOGY",
    PARENT_NAME: "KATMAI ONCOLOGY",
  },
  {
    HCP_NAME: "MINERVA BURGOS",
    PDRP: "NULL",
    TERRITORY: "MIAMI, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME: "ALABAMA ONCOLOGY",
    PARENT_NAME: "ALABAMA ONCOLOGY-ST VINCENTS",
  },
  {
    HCP_NAME: "SARAH YUE WANG",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "PARKVIEW CANCER INSTITUTE",
    PARENT_NAME: "PARKVIEW CANCER INSTITUTE",
  },
  {
    HCP_NAME: "JOHN PHILIP SCHWERKOSKE",
    PDRP: "N",
    TERRITORY: "SAN DIEGO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SIERRA HEMATOLOGY ONCOLOGY MEDICAL CENTER",
    PARENT_NAME: "SIERRA HEMATOLOGY ONCOLOGY MEDICAL CENTER",
  },
  {
    HCP_NAME: "GRACE CHANG",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SANTA MONICA HEMATOLOGY AND ONCOLOGY",
    PARENT_NAME: "SANTA MONICA HEMATOLOGY AND ONCOLOGY",
  },
  {
    HCP_NAME: "ESTHER LIU MONDO",
    PDRP: "N",
    TERRITORY: "DENVER, CO",
    REGION: "SOUTHWEST",
    CHILD_NAME: "BANNER FAMILY PHARMACY-MD ANDERSON #8026",
    PARENT_NAME: "BANNER CANCER CENTER SPECIALISTS LLC",
  },
  {
    HCP_NAME: "JENNIFER MINKYOUNG LEE",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
    PARENT_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
  },
  {
    HCP_NAME: "AMI N SHAH",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "NORTHWESTERN MEDICAL FACULTY FOUNDATION RADIOLOGY",
    PARENT_NAME: "NORTHWESTERN MEDICAL FACULTY FOUNDATION RADIOLOGY",
  },
  {
    HCP_NAME: "RADHAKRISHNA RAO VEGUNTA",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "SANFORD HEALTH ROGER MARIS CANCER CENTER",
    PARENT_NAME: "SANFORD HEALTH ROGER MARIS CANCER CENTER",
  },
  {
    HCP_NAME: "JAILAN ALAAELDIN ELAYOUBI",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "MCLAREN GREATER LANSING",
    PARENT_NAME: "KARMANOS CANCER INSTITUTE",
  },
  {
    HCP_NAME: "VINAY N MINOCHA",
    PDRP: "N",
    TERRITORY: "WEST PALM BEACH, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME: "UHEALTH MIAMI CORAL GABLES",
    PARENT_NAME: "UHEALTH MIAMI CORAL GABLES",
  },
  {
    HCP_NAME: "YAMAN SULEIMAN",
    PDRP: "N",
    TERRITORY: "ORLANDO, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME: "FLORIDA CANCER SPECIALISTS ORLANDO ORANGE",
    PARENT_NAME: "FLORIDA CANCER SPECIALISTS ORLANDO ORANGE",
  },
  {
    HCP_NAME: "WAEL GHALAYINI",
    PDRP: "N",
    TERRITORY: "CHARLESTON, SC",
    REGION: "SOUTHEAST",
    CHILD_NAME: "MUSC-FLORENCE MEDICAL CENTER",
    PARENT_NAME: "MUSC-FLORENCE MEDICAL CENTER",
  },
  {
    HCP_NAME: "TIEN PHUC P DO",
    PDRP: "N",
    TERRITORY: "RICHMOND, VA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "BON SECOURS MARYVIEW MEDICAL CENTER MEDICAL ONCOLOGY",
    PARENT_NAME: "BON SECOURS MARYVIEW MEDICAL CENTER MEDICAL ONCOLOGY",
  },
  {
    HCP_NAME: "AMRITA A DESAI",
    PDRP: "N",
    TERRITORY: "BEND, OR",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "CMH ONCOLOGY CLINIC PUBLIC HEALTH SERVICE OUTPATIENT",
    PARENT_NAME: "CMH ONCOLOGY CLINIC PUBLIC HEALTH SERVICE OUTPATIENT",
  },
  {
    HCP_NAME: "MAITRI KALRA",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "IU HEALTH BALL MEMORIAL CANCER CENTER",
    PARENT_NAME: "IU HEALTH SIMON CANCER CENTER",
  },
  {
    HCP_NAME: "NAMRATA M SHAH",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "AMERICAN HEALTH NETWORK HEMATOLOGY AND ONCOLOGY",
    PARENT_NAME: "AMERICAN HEALTH NETWORK HEMATOLOGY AND ONCOLOGY",
  },
  {
    HCP_NAME: "SYED ALI AKBAR",
    PDRP: "N",
    TERRITORY: "CLEVELAND, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "ALLEGHENY HEALTH NETWORK CANCER INSTITUTE KITTANNING",
    PARENT_NAME: "ALLEGHENY HEALTH NETWORK CANCER INSTITUTE KITTANNING",
  },
  {
    HCP_NAME: "NOELLE M BEIERLE",
    PDRP: "N",
    TERRITORY: "SEATTLE, WA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "BEACON CANCER CARE PLLC",
    PARENT_NAME: "BEACON CANCER CARE PLLC",
  },
  {
    HCP_NAME: "MING C LI",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME:
      "MISSION HERITAGE MEDICAL GROUP MISSION VIEJO-HEMATOLOGY AND ONCOLOGY",
    PARENT_NAME:
      "MISSION HERITAGE MEDICAL GROUP MISSION VIEJO-HEMATOLOGY AND ONCOLOGY",
  },
  {
    HCP_NAME: "RACHEE DANIELLE HATFIELD",
    PDRP: "N",
    TERRITORY: "COLUMBUS, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "JAMES CARE WOMENS CANCER CENTER",
    PARENT_NAME: "JAMES CARE WOMENS CANCER CENTER",
  },
  {
    HCP_NAME: "ANGEL MARIE FRANCINI",
    PDRP: "NULL",
    TERRITORY: "BOSTON, MA",
    REGION: "NORTHEAST",
    CHILD_NAME: "NORTHERN LIGHT EMMC LAFAYETTE FAMILY CANCER CARE",
    PARENT_NAME: "NORTHERN LIGHT EMMC LAFAYETTE FAMILY CANCER CARE",
  },
  {
    HCP_NAME: "MARY KATHLEEN BALL",
    PDRP: "NULL",
    TERRITORY: "CLEVELAND, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "HOPE CENTER FOR CANCER CARE YOUNGSTOWN",
    PARENT_NAME: "HOPE CENTER FOR CANCER CARE YOUNGSTOWN",
  },
  {
    HCP_NAME: "MARUJA PRINCESA HEISELMAN",
    PDRP: "NULL",
    TERRITORY: "CLEVELAND, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "UNIVERSITY HOSPITALS CLEVELAND MEDICAL CENTER",
    PARENT_NAME: "UNIVERSITY HOSPITALS CLEVELAND MEDICAL CENTER",
  },
  {
    HCP_NAME: "DENISE LYNN MALVASI",
    PDRP: "NULL",
    TERRITORY: "CLEVELAND, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "HOPE CENTER FOR CANCER CARE YOUNGSTOWN",
    PARENT_NAME: "HOPE CENTER FOR CANCER CARE YOUNGSTOWN",
  },
  {
    HCP_NAME: "XIMEI WANG",
    PDRP: "N",
    TERRITORY: "LOUISVILLE, KY",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "UC HEALTH PHYSICIANS OFFICE SOUTHWEST CHESTER",
    PARENT_NAME: "UNIVERSITY OF CINCINNATI MEDICAL CENTER",
  },
  {
    HCP_NAME: "KATHI E REYNOLDS",
    PDRP: "N",
    TERRITORY: "LOUISVILLE, KY",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "TRIHEALTH CANCER INSTITUTE KENWOOD",
    PARENT_NAME: "GOOD SAMARITAN INFUSION CENTER THOMAS CENTER",
  },
  {
    HCP_NAME: "WENDY KAY MCGRAW",
    PDRP: "NULL",
    TERRITORY: "CLEVELAND, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "MERCY HEALTH-ST ELIZABETH YOUNGSTOWN HOSPITAL",
    PARENT_NAME: "MERCY HEALTH-ST ELIZABETH YOUNGSTOWN HOSPITAL",
  },
  {
    HCP_NAME: "STEPHANIE NICOLE TRANTER",
    PDRP: "N",
    TERRITORY: "RALEIGH, NC",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "UNIVERSITY OF NORTH CAROLINA HOSPITALS",
    PARENT_NAME: "UNIVERSITY OF NORTH CAROLINA HOSPITALS",
  },
  {
    HCP_NAME: "ELIZABETH M MURPHY",
    PDRP: "N",
    TERRITORY: "COLUMBUS, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "SOIN INFUSION PHARMACY",
    PARENT_NAME: "KETTERING CANCER CARE",
  },
  {
    HCP_NAME: "BRITTANY N SWEIGART",
    PDRP: "N",
    TERRITORY: "COLUMBUS, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "OHIOHEALTH RIVERSIDE METHODIST HOSPITAL",
    PARENT_NAME: "OHIOHEALTH RIVERSIDE METHODIST HOSPITAL",
  },
  {
    HCP_NAME: "YVONNE NELSON",
    PDRP: "NULL",
    TERRITORY: "CLEVELAND, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "HOPE CENTER FOR CANCER CARE YOUNGSTOWN",
    PARENT_NAME: "HOPE CENTER FOR CANCER CARE YOUNGSTOWN",
  },
  {
    HCP_NAME: "MELISSA LYNNE WILLIS",
    PDRP: "NULL",
    TERRITORY: "COLUMBUS, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "AULTMAN HOSPITAL",
    PARENT_NAME: "AULTMAN HOSPITAL",
  },
  {
    HCP_NAME: "THAN AYE",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "MONUMENT HEALTH CANCER CARE INSTITUTE",
    PARENT_NAME: "MONUMENT HEALTH CANCER CARE INSTITUTE",
  },
  {
    HCP_NAME: "MELISSA LYNN SULLIVAN",
    PDRP: "N",
    TERRITORY: "COLUMBUS, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "JAMES CARE WOMENS CANCER CENTER",
    PARENT_NAME: "JAMES CARE WOMENS CANCER CENTER",
  },
  {
    HCP_NAME: "KRISTIN MARIE SOBECK",
    PDRP: "N",
    TERRITORY: "BROOKLYN/LONG ISLAND",
    REGION: "NORTHEAST",
    CHILD_NAME: "LONG ISLAND MEDICAL ONCOLOGY HEMATOLOGY ASSOCIATES",
    PARENT_NAME: "LONG ISLAND MEDICAL ONCOLOGY HEMATOLOGY ASSOCIATES",
  },
  {
    HCP_NAME: "ELENA GALLAGHER O'ROURKE",
    PDRP: "N",
    TERRITORY: "MANHATTAN/NJ",
    REGION: "NORTHEAST",
    CHILD_NAME: "THE MOUNT SINAI HOSPITAL",
    PARENT_NAME: "THE MOUNT SINAI HOSPITAL",
  },
  {
    HCP_NAME: "MONIFA POWELL",
    PDRP: "N",
    TERRITORY: "MANHATTAN/NJ",
    REGION: "NORTHEAST",
    CHILD_NAME: "MOUNT SINAI HOSPITAL DUBIN BREAST CENTER MAMMOGRAPHY",
    PARENT_NAME: "MOUNT SINAI HOSPITAL DUBIN BREAST CENTER MAMMOGRAPHY",
  },
  {
    HCP_NAME: "MICHELLE SOYEUN LYN",
    PDRP: "N",
    TERRITORY: "MANHATTAN/NJ",
    REGION: "NORTHEAST",
    CHILD_NAME: "THE MOUNT SINAI HOSPITAL",
    PARENT_NAME: "THE MOUNT SINAI HOSPITAL",
  },
  {
    HCP_NAME: "CRYSTAL LORRAINE ROGERS",
    PDRP: "N",
    TERRITORY: "BROOKLYN/LONG ISLAND",
    REGION: "NORTHEAST",
    CHILD_NAME: "NYC HEALTH + HOSPITALS BELLEVUE",
    PARENT_NAME: "NYC HEALTH + HOSPITALS BELLEVUE",
  },
  {
    HCP_NAME: "ANDREW IYPE KOVOOR",
    PDRP: "N",
    TERRITORY: "DALLAS, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "TEXAS ONCOLOGY PLANO WEST",
    PARENT_NAME: "TEXAS ONCOLOGY BAYLOR SAMMONS CENTER BONE MARROW TRANSPLANT",
  },
  {
    HCP_NAME: "MONICA ADRIANA DIAZ",
    PDRP: "N",
    TERRITORY: "SAN ANTONIO, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "TEXAS ONCOLOGY-EL PASO CANCER TREATMENT CENTER JOE BATTLE",
    PARENT_NAME: "TEXAS ONCOLOGY BAYLOR SAMMONS CENTER BONE MARROW TRANSPLANT",
  },
  {
    HCP_NAME: "ARCHANA NAYANI",
    PDRP: "N",
    TERRITORY: "DES MOINES, IA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "SPRINGFIELD CLINIC 1ST-900 BUILDING",
    PARENT_NAME: "SPRINGFIELD CLINIC 1ST-900 BUILDING",
  },
  {
    HCP_NAME: "RAJU K VADDEPALLY",
    PDRP: "N",
    TERRITORY: "SAN DIEGO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "YUMA REGIONAL MEDICAL CENTER",
    PARENT_NAME: "YUMA REGIONAL MEDICAL CENTER",
  },
  {
    HCP_NAME: "LEAH ZHREBKER",
    PDRP: "N",
    TERRITORY: "DALLAS, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "TEXAS ONCOLOGY PHARMACY-HEB",
    PARENT_NAME: "TEXAS ONCOLOGY BAYLOR SAMMONS CENTER BONE MARROW TRANSPLANT",
  },
  {
    HCP_NAME: "DEVIN B MALIK",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "HENRY FORD HOSPITAL",
    PARENT_NAME: "HENRY FORD HOSPITAL",
  },
  {
    HCP_NAME: "SARAH ZAINAB HASSAN",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "OC BLOOD AND CANCER CARE",
    PARENT_NAME: "OC BLOOD AND CANCER CARE",
  },
  {
    HCP_NAME: "SRI BHARATHI YADLAPALLI",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "IHA HEMATOLOGY ONCOLOGY CONSULTANTS ANN ARBOR",
    PARENT_NAME: "IHA HEMATOLOGY ONCOLOGY CONSULTANTS ANN ARBOR",
  },
  {
    HCP_NAME: "KELLY L MILLER",
    PDRP: "N",
    TERRITORY: "COLUMBUS, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "PREMIER UROLOGY SPECIALISTS",
    PARENT_NAME: "DAYTON PHYSICIANS-GREATER DAYTON CANCER CENTER",
  },
  {
    HCP_NAME: "MOHAMMED S AZEEM",
    PDRP: "N",
    TERRITORY: "DES MOINES, IA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "EDWARD HEMATOLOGY ONCOLOGY GROUP",
    PARENT_NAME: "EDWARD HEMATOLOGY ONCOLOGY GROUP",
  },
  {
    HCP_NAME: "JACKLYN M NEMUNAITIS",
    PDRP: "N",
    TERRITORY: "PHOENIX, AZ",
    REGION: "SOUTHWEST",
    CHILD_NAME: "UNIVERSITY OF NEW MEXICO COMPREHENSIVE CANCER CENTER",
    PARENT_NAME: "UNIVERSITY OF NEW MEXICO COMPREHENSIVE CANCER CENTER",
  },
  {
    HCP_NAME: "NIKITA TUSHAR AMIN",
    PDRP: "N",
    TERRITORY: "ATLANTA, GA",
    REGION: "SOUTHEAST",
    CHILD_NAME: "PIEDMONT CANCER INSTITUTE ATLANTA PHARMACY",
    PARENT_NAME: "PIEDMONT CANCER INSTITUTE ATLANTA PHARMACY",
  },
  {
    HCP_NAME: "KYLE RICHARD GREENE",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "THE ONCOLOGY INSTITUTE CERRITOS-CORPORATE OFFICE",
    PARENT_NAME: "THE ONCOLOGY INSTITUTE OF HOPE AND INNOVATION ADMIN OFFICE",
  },
  {
    HCP_NAME: "NICHOLAS P MCANDREW",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "CEDARS SINAI COMPREHENSIVE CANCER CENTER PHARMACY",
    PARENT_NAME: "CEDARS SINAI COMPREHENSIVE CANCER CENTER PHARMACY",
  },
  {
    HCP_NAME: "KENNETH LEE ANGELINO",
    PDRP: "N",
    TERRITORY: "BROOKLYN/LONG ISLAND",
    REGION: "NORTHEAST",
    CHILD_NAME: "SOUTH NASSAU ONCOLOGY PRACTICE",
    PARENT_NAME: "SOUTH NASSAU ONCOLOGY PRACTICE",
  },
  {
    HCP_NAME: "KAMRAN A AHMED",
    PDRP: "N",
    TERRITORY: "TAMPA, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME:
      "H LEE MOFFITT CANCER CENTER RICHARD SCHULZE OUTPATIENT CENTER MCKINLEY CAMPUS",
    PARENT_NAME:
      "H LEE MOFFITT CANCER CENTER RICHARD SCHULZE OUTPATIENT CENTER MCKINLEY CAMPUS",
  },
  {
    HCP_NAME: "SARAH LENOIR SAMMONS",
    PDRP: "N",
    TERRITORY: "RALEIGH, NC",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "DUKE COLON AND RECTAL SURGERY",
    PARENT_NAME: "DUKE CANCER CENTER",
  },
  {
    HCP_NAME: "CHRYSTAL ANN LANDRY",
    PDRP: "N",
    TERRITORY: "BROOKLYN/LONG ISLAND",
    REGION: "NORTHEAST",
    CHILD_NAME: "CENTER FOR ADVANCED MEDICINE MONTER CANCER CENTER",
    PARENT_NAME: "NORTHWELL IMBERT CANCER CENTER",
  },
  {
    HCP_NAME: "ADITYA RAI SARVARIA",
    PDRP: "N",
    TERRITORY: "SAN DIEGO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SCRIPPS GREEN CANCER CENTER",
    PARENT_NAME: "SCRIPPS GREEN CANCER CENTER",
  },
  {
    HCP_NAME: "YULIAN KHAGI",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "CITY OF HOPE COMPREHENSIVE CANCER CENTER-DUARTE",
    PARENT_NAME: "CITY OF HOPE COMPREHENSIVE CANCER CENTER-DUARTE",
  },
  {
    HCP_NAME: "MELANIE JEAN CLARK",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "PARKVIEW CANCER INSTITUTE",
    PARENT_NAME: "PARKVIEW CANCER INSTITUTE",
  },
  {
    HCP_NAME: "MICHELLE ALISON LEVY",
    PDRP: "N",
    TERRITORY: "DENVER, CO",
    REGION: "SOUTHWEST",
    CHILD_NAME:
      "ROCKY MOUNTAIN CANCER CENTERS-DENVER ROSE MEDICAL CENTER CAMPUS",
    PARENT_NAME:
      "ROCKY MOUNTAIN CANCER CENTERS-DENVER ROSE MEDICAL CENTER CAMPUS",
  },
  {
    HCP_NAME: "ROHAN SHARMA",
    PDRP: "N",
    TERRITORY: "PHOENIX, AZ",
    REGION: "SOUTHWEST",
    CHILD_NAME: "NORTHWEST MEDICAL SPECIALTIES PLLC",
    PARENT_NAME: "NORTHWEST MEDICAL SPECIALTIES",
  },
  {
    HCP_NAME: "JAY P LOPEZ",
    PDRP: "N",
    TERRITORY: "SEATTLE, WA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "SWEDISH CANCER INSTITUTE AT SWEDISH ISSAQUAH",
    PARENT_NAME: "SWEDISH CANCER INSTITUTE AT SWEDISH ISSAQUAH",
  },
  {
    HCP_NAME: "NATASHA BEATRICE HUNTER",
    PDRP: "N",
    TERRITORY: "SEATTLE, WA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "SCCA AT EVERGREENHEALTH",
    PARENT_NAME: "SEATTLE CANCER CARE ALLIANCE",
  },
  {
    HCP_NAME: "KARTHIK V GIRIDHAR",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "MAYO CLINIC HEALTH SYSTEM",
    PARENT_NAME: "MAYO CLINIC HEALTH SYSTEM",
  },
  {
    HCP_NAME: "LAUREN E JUNEJA",
    PDRP: "N",
    TERRITORY: "JACKSON, MS",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "OUR LADY OF THE LAKE INFUSION CENTER",
    PARENT_NAME: "OUR LADY OF THE LAKE INFUSION CENTER",
  },
  {
    HCP_NAME: "ARIELLE L HEEKE",
    PDRP: "N",
    TERRITORY: "CHARLOTTE, NC",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "THE CHARLOTTE-MECKLENBURG HOSPITAL AUTHORITY",
    PARENT_NAME: "LEVINE CANCER INSTITUTE-ATRIUM HEALTH",
  },
  {
    HCP_NAME: "JOSE E ABREU ARBELO",
    PDRP: "N",
    TERRITORY: "MIAMI, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME: "AUXILIO MUTUO HOSPITAL",
    PARENT_NAME: "AUXILIO MUTUO HOSPITAL",
  },
  {
    HCP_NAME: "DOUGLAS KANTER MARKS",
    PDRP: "N",
    TERRITORY: "BROOKLYN/LONG ISLAND",
    REGION: "NORTHEAST",
    CHILD_NAME: "WINTHROP ORTHOPEDICS ASSOCIATES-GARDEN CITY",
    PARENT_NAME: "NYU LANGONE CANCER CENTER",
  },
  {
    HCP_NAME: "JOHN JAMES GRAHAM",
    PDRP: "N",
    TERRITORY: "COLUMBUS, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "BLOOD AND CANCER CENTER INC",
    PARENT_NAME: "BLOOD AND CANCER CENTER INC",
  },
  {
    HCP_NAME: "ASHREI YEHUDA BAYEWITZ",
    PDRP: "N",
    TERRITORY: "BROOKLYN/LONG ISLAND",
    REGION: "NORTHEAST",
    CHILD_NAME: "WINTHROP ORTHOPEDICS ASSOCIATES-GARDEN CITY",
    PARENT_NAME: "NYU LANGONE CANCER CENTER",
  },
  {
    HCP_NAME: "SHELLY CHRISTIANSEN SHAND",
    PDRP: "N",
    TERRITORY: "CHARLESTON, SC",
    REGION: "SOUTHEAST",
    CHILD_NAME: "CHARLESTON ONCOLOGY",
    PARENT_NAME: "CHARLESTON ONCOLOGY",
  },
  {
    HCP_NAME: "RODOLFO GUTIERREZ",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "THE ANGELES CLINIC AND RESEARCH INSTITUTE WEST LOS ANGELES",
    PARENT_NAME: "THE ANGELES CLINIC AND RESEARCH INSTITUTE WEST LOS ANGELES",
  },
  {
    HCP_NAME: "MELISSA ANN CRAWLEY",
    PDRP: "N",
    TERRITORY: "SAN ANTONIO, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "TEXAS ONCOLOGY-SAN ANTONIO MEDICAL CENTER",
    PARENT_NAME: "TEXAS ONCOLOGY BAYLOR SAMMONS CENTER BONE MARROW TRANSPLANT",
  },
  {
    HCP_NAME: "DAVID BOLOS",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
    PARENT_NAME: "LOS ANGELES COUNTY OLIVE VIEW-UCLA MEDICAL CENTER",
  },
  {
    HCP_NAME: "ERIN LEE SCHWAB",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "CANCER AND HEMATOLOGY CENTERS OF WESTERN MICHIGAN PHARMACY",
    PARENT_NAME: "CANCER AND HEMATOLOGY CENTERS OF WESTERN MICHIGAN PHARMACY",
  },
  {
    HCP_NAME: "NATALIE WALLIS HARPER",
    PDRP: "N",
    TERRITORY: "LOUISVILLE, KY",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "BAPTIST HEALTH MEDICAL GROUP CANCER CARE CENTER",
    PARENT_NAME: "BAPTIST HEALTH MEDICAL GROUP CANCER CARE CENTER",
  },
  {
    HCP_NAME: "FAUZIA RIAZ",
    PDRP: "N",
    TERRITORY: "SAN FRANCISCO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "STANFORD HOSPITAL",
    PARENT_NAME: "STANFORD HOSPITAL",
  },
  {
    HCP_NAME: "CHRISTINE S SAM",
    PDRP: "N",
    TERRITORY: "TAMPA, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME:
      "H LEE MOFFITT CANCER CENTER RICHARD SCHULZE OUTPATIENT CENTER MCKINLEY CAMPUS",
    PARENT_NAME:
      "H LEE MOFFITT CANCER CENTER RICHARD SCHULZE OUTPATIENT CENTER MCKINLEY CAMPUS",
  },
  {
    HCP_NAME: "GORDON FREDERICK WADGE",
    PDRP: "N",
    TERRITORY: "JACKSON, MS",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "OCHSNER MEDICAL CENTER",
    PARENT_NAME: "OCHSNER MEDICAL CENTER",
  },
  {
    HCP_NAME: "OJAS HARIHAR VYAS",
    PDRP: "N",
    TERRITORY: "SAN ANTONIO, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "UT MEDICINE DERMATOLOGY CTRC",
    PARENT_NAME: "UT MEDICINE DERMATOLOGY CTRC",
  },
  {
    HCP_NAME: "CANDACE BAVETTE MAINOR",
    PDRP: "N",
    TERRITORY: "BALTIMORE, MD",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "MEDSTAR GEORGETOWN UNIVERSITY HOSPITAL",
    PARENT_NAME: "MEDSTAR GEORGETOWN UNIVERSITY HOSPITAL",
  },
  {
    HCP_NAME: "TARAH JEAN BALLINGER",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "IU HEALTH SIMON CANCER CENTER",
    PARENT_NAME: "IU HEALTH SIMON CANCER CENTER",
  },
  {
    HCP_NAME: "OMER ILYAS",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "COMMUNITY CANCER INSTITUTE",
    PARENT_NAME: "COMMUNITY CANCER INSTITUTE",
  },
  {
    HCP_NAME: "AUSTIN IAN POOLE",
    PDRP: "N",
    TERRITORY: "DENVER, CO",
    REGION: "SOUTHWEST",
    CHILD_NAME:
      "ROCKY MOUNTAIN CANCER CENTERS-DENVER ROSE MEDICAL CENTER CAMPUS",
    PARENT_NAME:
      "ROCKY MOUNTAIN CANCER CENTERS-DENVER ROSE MEDICAL CENTER CAMPUS",
  },
  {
    HCP_NAME: "KIMBERLY SARA STRICKLAND",
    PDRP: "N",
    TERRITORY: "CHARLOTTE, NC",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "NOVANT HEALTH CANCER SPECIALISTS CHARLOTTE",
    PARENT_NAME: "NOVANT HEALTH CANCER SPECIALISTS CHARLOTTE",
  },
  {
    HCP_NAME: "PAUL F LA PORTE",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "CEDARS SINAI COMPREHENSIVE CANCER CENTER PHARMACY",
    PARENT_NAME: "CEDARS SINAI COMPREHENSIVE CANCER CENTER PHARMACY",
  },
  {
    HCP_NAME: "PHILIP D POORVU",
    PDRP: "N",
    TERRITORY: "BOSTON, MA",
    REGION: "NORTHEAST",
    CHILD_NAME: "DANA FARBER CANCER CENTER",
    PARENT_NAME: "DANA FARBER CANCER CENTER",
  },
  {
    HCP_NAME: "PREETHI K JOHN",
    PDRP: "N",
    TERRITORY: "DALLAS, TX",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "UT COMPREHENSIVE CANCER CENTER",
    PARENT_NAME: "SIMMONS COMPREHENSIVE CANCER CENTER",
  },
  {
    HCP_NAME: "RUBENS CHING-CHIA CHANG",
    PDRP: "N",
    TERRITORY: "DENVER, CO",
    REGION: "SOUTHWEST",
    CHILD_NAME: "UNIVERSITY OF COLORADO HOSPITAL",
    PARENT_NAME: "UNIVERSITY OF COLORADO HOSPITAL",
  },
  {
    HCP_NAME: "SOBIA OZAIR",
    PDRP: "N",
    TERRITORY: "JACKSON, MS",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "OUR LADY OF THE LAKE INFUSION CENTER",
    PARENT_NAME: "OUR LADY OF THE LAKE INFUSION CENTER",
  },
  {
    HCP_NAME: "ELIZABETH M KANDER",
    PDRP: "N",
    TERRITORY: "COLUMBUS, OH",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "COLUMBUS ONCOLOGY ASSOCIATES INC",
    PARENT_NAME: "COLUMBUS ONCOLOGY ASSOCIATES INC",
  },
  {
    HCP_NAME: "JEREMY LORBER",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "CEDARS SINAI COMPREHENSIVE CANCER CENTER PHARMACY",
    PARENT_NAME: "CEDARS SINAI COMPREHENSIVE CANCER CENTER PHARMACY",
  },
  {
    HCP_NAME: "NIKHIL MUKHI",
    PDRP: "N",
    TERRITORY: "OKLAHOMA CITY, OK",
    REGION: "SOUTH CENTRAL",
    CHILD_NAME: "SAINT FRANCIS CANCER CENTER",
    PARENT_NAME: "SAINT FRANCIS CANCER CENTER",
  },
  {
    HCP_NAME: "JAMES THOMAS LINK",
    PDRP: "N",
    TERRITORY: "DENVER, CO",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SLO ONCOLOGY AND HEMATOLOGY HEALTH CENTER",
    PARENT_NAME: "SLO ONCOLOGY AND HEMATOLOGY HEALTH CENTER",
  },
  {
    HCP_NAME: "AVAN J ARMAGHANI",
    PDRP: "N",
    TERRITORY: "TAMPA, FL",
    REGION: "SOUTHEAST",
    CHILD_NAME:
      "H LEE MOFFITT CANCER CENTER RICHARD SCHULZE OUTPATIENT CENTER MCKINLEY CAMPUS",
    PARENT_NAME:
      "H LEE MOFFITT CANCER CENTER RICHARD SCHULZE OUTPATIENT CENTER MCKINLEY CAMPUS",
  },
  {
    HCP_NAME: "CHELSEA D GAWRYLETZ",
    PDRP: "N",
    TERRITORY: "DENVER, CO",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SCL HEALTH PHARMACY SERVICES-FRANKLIN",
    PARENT_NAME: "SCL HEALTH PHARMACY SERVICES-FRANKLIN",
  },
  {
    HCP_NAME: "PAMELA S HOLWEGNER",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "TRINITY HEALTH CANCER CARE",
    PARENT_NAME: "TRINITY HEALTH CANCER CARE",
  },
  {
    HCP_NAME: "BRITTANY L SIONTIS",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "MAYO CLINIC HEALTH SYSTEM",
    PARENT_NAME: "MAYO CLINIC HEALTH SYSTEM",
  },
  {
    HCP_NAME: "SOYOUNG PARK",
    PDRP: "N",
    TERRITORY: "PHOENIX, AZ",
    REGION: "SOUTHWEST",
    CHILD_NAME: "BANNER CANCER CENTER SPECIALISTS LLC",
    PARENT_NAME: "BANNER CANCER CENTER SPECIALISTS LLC",
  },
  {
    HCP_NAME: "ERIC HO-YIN LEE",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "COMPASSIONATE CANCER CARE MEDICAL GROUP FOUNTAIN VALLEY",
    PARENT_NAME: "COMPASSIONATE CANCER CARE MEDICAL GROUP CORONA",
  },
  {
    HCP_NAME: "YUESHENG JAMES QU",
    PDRP: "N",
    TERRITORY: "ATLANTA, GA",
    REGION: "SOUTHEAST",
    CHILD_NAME: "NORTHWEST GEORGIA ONCOLOGY CENTERS WELLSTAR-CARTERSVILLE",
    PARENT_NAME: "NORTHWEST GEORGIA ONCOLOGY CENTERS WELLSTAR-CARTERSVILLE",
  },
  {
    HCP_NAME: "MARKIE N MEMINGER",
    PDRP: "N",
    TERRITORY: "DES MOINES, IA",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "NORTHWESTERN MEDICAL FACULTY FOUNDATION RADIOLOGY",
    PARENT_NAME: "NORTHWESTERN MEDICAL FACULTY FOUNDATION RADIOLOGY",
  },
  {
    HCP_NAME: "FARAH F QUYYUMI",
    PDRP: "N",
    TERRITORY: "BAKERSFIELD, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "THE ONCOLOGY INSTITUTE CERRITOS-CORPORATE OFFICE",
    PARENT_NAME: "THE ONCOLOGY INSTITUTE OF HOPE AND INNOVATION ADMIN OFFICE",
  },
  {
    HCP_NAME: "ALICIA MASTON COFFIN",
    PDRP: "NULL",
    TERRITORY: "SYRACUSE, NY",
    REGION: "NORTHEAST",
    CHILD_NAME: "URMC HOME CARE PHARMACY",
    PARENT_NAME: "URMC HOME CARE PHARMACY",
  },
  {
    HCP_NAME: "ANKIT ANAND",
    PDRP: "N",
    TERRITORY: "PHOENIX, AZ",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SAN JUAN ONCOLOGY ASSOCIATES PC",
    PARENT_NAME: "SAN JUAN ONCOLOGY ASSOCIATES PC",
  },
  {
    HCP_NAME: "IGOR MEDIC",
    PDRP: "N",
    TERRITORY: "SAN DIEGO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SCRIPPS GREEN CANCER CENTER",
    PARENT_NAME: "SCRIPPS GREEN CANCER CENTER",
  },
  {
    HCP_NAME: "HENRY P IGID",
    PDRP: "N",
    TERRITORY: "DENVER, CO",
    REGION: "SOUTHWEST",
    CHILD_NAME: "COMPREHENSIVE CANCER CENTER-CENTRAL VALLEY",
    PARENT_NAME: "COMPREHENSIVE CANCER CENTER-CENTRAL VALLEY",
  },
  {
    HCP_NAME: "LIN HAO",
    PDRP: "N",
    TERRITORY: "DENVER, CO",
    REGION: "SOUTHWEST",
    CHILD_NAME: "BANNER FAMILY PHARMACY-MD ANDERSON #8026",
    PARENT_NAME: "BANNER CANCER CENTER SPECIALISTS LLC",
  },
  {
    HCP_NAME: "ALEXANDRA D TUUK",
    PDRP: "N",
    TERRITORY: "ATLANTA, GA",
    REGION: "SOUTHEAST",
    CHILD_NAME: "NORTHWEST GEORGIA ONCOLOGY CENTERS WELLSTAR-CARTERSVILLE",
    PARENT_NAME: "NORTHWEST GEORGIA ONCOLOGY CENTERS WELLSTAR-CARTERSVILLE",
  },
  {
    HCP_NAME: "VERONICA CASTELLANO",
    PDRP: "N",
    TERRITORY: "KANSAS CITY, MO",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "UNIVERSITY OF KANSAS HOSPITAL",
    PARENT_NAME: "THE UNIVERSITY OF KANSAS CANCER CENTER",
  },
  {
    HCP_NAME: "DIANE M STUMVOLL",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "AURORA CANCER CARE",
    PARENT_NAME: "ADVOCATE AURORA HEALTH",
  },
  {
    HCP_NAME: "MELISSA J PAASCH",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "AURORA HEALTHCARE VINCE LOMBARDI CANCER CLINIC",
    PARENT_NAME: "ADVOCATE AURORA HEALTH",
  },
  {
    HCP_NAME: "LOYDA E BRAITHWAITE",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "UW HEALTH ACO INC",
    PARENT_NAME: "UW HEALTH ACO INC",
  },
  {
    HCP_NAME: "ANDREA L EBBEN",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "FROEDTERT AND THE MEDICAL COLLEGE OF WISCONSIN",
    PARENT_NAME: "FROEDTERT AND THE MEDICAL COLLEGE OF WISCONSIN",
  },
  {
    HCP_NAME: "OLIVERA CATIC",
    PDRP: "N",
    TERRITORY: "MINNEAPOLIS, MN",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "AURORA CANCER CARE",
    PARENT_NAME: "ADVOCATE AURORA HEALTH",
  },
  {
    HCP_NAME: "YAMEEN M RASHID",
    PDRP: "N",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "FRANCISCAN HEALTH MUNSTER",
    PARENT_NAME: "FRANCISCAN HEALTH MUNSTER",
  },
  {
    HCP_NAME: "SAYEH MOAZAMI LAVASANI",
    PDRP: "N",
    TERRITORY: "LOS ANGELES, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "CITY OF HOPE COMPREHENSIVE CANCER CENTER-DUARTE",
    PARENT_NAME: "CITY OF HOPE COMPREHENSIVE CANCER CENTER-DUARTE",
  },
  {
    HCP_NAME: "JORDAN ANDREW HENDERSON",
    PDRP: "N",
    TERRITORY: "CHARLESTON, SC",
    REGION: "SOUTHEAST",
    CHILD_NAME:
      "COASTAL CANCER CENTER ASSOCIATED MEDICAL SPECIALISTS MYRTLE BEACH",
    PARENT_NAME:
      "COASTAL CANCER CENTER ASSOCIATED MEDICAL SPECIALISTS MYRTLE BEACH",
  },
  {
    HCP_NAME: "MALLORY N SANDRIDGE",
    PDRP: "N",
    TERRITORY: "SAN FRANCISCO, CA",
    REGION: "SOUTHWEST",
    CHILD_NAME: "SVMC CANCER CARE",
    PARENT_NAME: "SVMC CANCER CARE",
  },
  {
    HCP_NAME: "CINDY HALL KAPINOS",
    PDRP: "N",
    TERRITORY: "RICHMOND, VA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "BON SECOURS CANCER INSTITUTE AT MEMORIAL REGIONAL",
    PARENT_NAME: "BON SECOURS-RICHMOND COMMUNITY HOSPITAL",
  },
  {
    HCP_NAME: "GADE R SYAMALA",
    PDRP: "N",
    TERRITORY: "RICHMOND, VA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "VIRGINIA CANCER INSTITUTE WEST END",
    PARENT_NAME: "VIRGINIA CANCER INSTITUTE WEST END",
  },
  {
    HCP_NAME: "SUSAN C HERNDON",
    PDRP: "N",
    TERRITORY: "RICHMOND, VA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "VCU TAPPAHANNOCK HOSPITAL",
    PARENT_NAME: "VCU HEALTH MAIN HOSPITAL",
  },
  {
    HCP_NAME: "JANA HURT HANNY",
    PDRP: "N",
    TERRITORY: "RICHMOND, VA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "BON SECOURS CANCER INSTITUTE AT MEMORIAL REGIONAL",
    PARENT_NAME: "BON SECOURS-RICHMOND COMMUNITY HOSPITAL",
  },
  {
    HCP_NAME: "JENNIFER H FOSTER",
    PDRP: "N",
    TERRITORY: "RICHMOND, VA",
    REGION: "MID ATLANTIC",
    CHILD_NAME: "BLUE RIDGE CANCER CARE ROANOKE",
    PARENT_NAME: "BLUE RIDGE CANCER CARE ROANOKE",
  },
  {
    HCP_NAME: "BRYAN FEAGAN",
    PDRP: "NULL",
    TERRITORY: "KANSAS CITY, MO",
    REGION: "GREAT NORTHWEST",
    CHILD_NAME: "FREEMAN CORNELL-BESHORE CANCER INSTITUTE",
    PARENT_NAME: "FREEMAN CORNELL-BESHORE CANCER INSTITUTE",
  },
  {
    HCP_NAME: "STEPHANIE NEHL",
    PDRP: "NULL",
    TERRITORY: "DETROIT, MI",
    REGION: "TENNESSEE VALLEY",
    CHILD_NAME: "MICHIANA HEMATOLOGY ONCOLOGY PC",
    PARENT_NAME: "MICHIANA HEMATOLOGY ONCOLOGY PC",
  },
];

const d_frame = (data) => {
  let new_data = [];

  for (let i = 0; i < data.length; i++) {
    let ele = {};
    let flag = 1;
    for (let j = 0; j < new_data.length; j++) {
      if (new_data[j].parent_name === data[i].PARENT_NAME) {
        for (let k = 0; k < new_data[j].HCO_name.length; k++) {
          if (new_data[j].HCO_name[k].name === data[i].CHILD_NAME) {
            let hcp_ele = {};
            hcp_ele.hcp = data[i].HCP_NAME;
            hcp_ele.territory = data[i].TERRITORY;
            hcp_ele.pdrp = data[i].PDRP;
            hcp_ele.region = data[i].REGION;
            new_data[j].HCO_name[k].HCP_name.push(hcp_ele);
            flag = 0;
          }
        }
        if (flag === 1) {
          let hco_ele = {};
          hco_ele.name = data[i].CHILD_NAME;
          hco_ele.HCP_name = [];
          let hcp_ele = {};
          hcp_ele.hcp = data[i].HCP_NAME;
          hcp_ele.territory = data[i].TERRITORY;
          hcp_ele.pdrp = data[i].PDRP;
          hcp_ele.region = data[i].REGION;
          hco_ele.HCP_name.push(hcp_ele);
          new_data[j].HCO_name.push(hco_ele);

          flag = 0;
          break;
        }
      }
    }
    if (flag === 1) {
      ele.parent_name = data[i].PARENT_NAME;
      ele.HCO_name = [];
      let new_ele1 = {};
      new_ele1.name = data[i].CHILD_NAME;
      new_ele1.HCP_name = [];

      let new_ele2 = {};
      new_ele2.hcp = data[i].HCP_NAME;
      new_ele2.territory = data[i].TERRITORY;
      new_ele2.region = data[i].REGION;
      new_ele2.pdrp = data[i].PDRP;

      new_ele1.HCP_name.push(new_ele2);
      ele.HCO_name.push(new_ele1);
      new_data.push(ele);
    }
  }
  return new_data;
};

const data1 = d_frame(data);
console.log(data1);

const data2 = [
  {
    REGION: "GREAT NORTHWEST",
    TERRITORY: [
      "BEND, OR",
      "DES MOINES, IA",
      "KANSAS CITY, MO",
      "MINNEAPOLIS, MN",
      "SEATTLE, WA",
    ],
  },
  {
    REGION: "MID ATLANTIC",
    TERRITORY: [
      "BALTIMORE, MD",
      "CHARLOTTE, NC",
      "PHILADELPHIA, PA",
      "RALEIGH, NC",
      "RICHMOND, VA",
    ],
  },
  {
    REGION: "NORTHEAST",
    TERRITORY: [
      "BOSTON, MA",
      "BROOKLYN/LONG ISLAND",
      "HARTFORD, CT",
      "SYRACUSE, NY",
      "WHITE PLAINS, NY",
    ],
  },
  {
    REGION: "SOUTH CENTRAL",
    TERRITORY: [
      "BIRMINGHAM, AL",
      "DALLAS, TX",
      "HOUSTON, TX",
      "OKLAHOMA CITY, OK",
      "SAN ANTONIO, TX",
    ],
  },
  {
    REGION: "SOUTHEAST",
    TERRITORY: [
      "ATLANTA, GA",
      "CHARLESTON, SC",
      "MIAMI, FL",
      "ORLANDO, FL",
      "TAMPA, FL",
      "WEST PALM BEACH, FL",
    ],
  },
  {
    REGION: "SOUTHWEST",
    TERRITORY: [
      "BAKERSFIELD, CA",
      "DENVER, CO",
      "LOS ANGELES, CA",
      "PHOENIX, AZ",
      "SAN DIEGO, CA",
      "SAN FRANCISCO, CA",
    ],
  },
  {
    REGION: "TENNESSEE VALLEY",
    TERRITORY: [
      "CLEVELAND, OH",
      "COLUMBUS, OH",
      "DETROIT, MI",
      "LOUISVILLE, KY",
    ],
  },
];

// Implementing region and territory dropdowns

for (let i = 0; i < data2.length; i++) {
  $("#region").append(
    `<option value="${data2[i].REGION}">${data2[i].REGION}</option>`
  );
}

$("#region").on("change", () => {
  $("#territory").html(`<option value="all"  selected hidden>Select</option>`);
  let value = $("#region").val();
  for (let i = 0; i < data2.length; i++) {
    if (data2[i].REGION === value) {
      for (let j = 0; j < data2[i].TERRITORY.length; j++) {
        $("#territory").append(
          `<option value="${data2[i].TERRITORY[j]}">${data2[i].TERRITORY[j]}</option>`
        );
      }
    }
  }
});

// Adding table
const table = (data) => {
  for (let i = 0; i < data.length; i++) {
    $(".table-body").append(
      `
      <tr>
          <td class="parent" id="${i}"><span id="btn${i}" class="element text-info">+</span>${data[i].parent_name}</td>
          
      </tr>
      <tr class="child-tab child-table" id="tab${i}">
          <td class="child-data" >
              <table class="table " id="${i}table">                
              </table>
          </td>
      </tr>`
    );

    for (let j = 0; j < data[i].HCO_name.length; j++) {
      $(`#${i}table`).append(
        `<tr>
          <td class="child" id="${i}${j}"><span id="btn${i}${j}" class="element text-info">+</span>${data[i].HCO_name[j].name}</td>
          
         </tr>
         <tr class="HCP-tab" id="tab${i}${j}">
          <td>
              <table class="table" id="table${i}${j}">                
              </table>
          </td>
      </tr>`
      );
      for (let k = 0; k < data[i].HCO_name[j].HCP_name.length; k++) {
        $(`#table${i}${j}`).append(
          `<tr>
          
          <td><span>•</span>${
            data[i].HCO_name[j].HCP_name[k].pdrp === "Y"
              ? "PDRP Prescriber"
              : data[i].HCO_name[j].HCP_name[k].hcp
          }</td>
          <td>${data[i].HCO_name[j].HCP_name[k].region}</td>
          <td>${data[i].HCO_name[j].HCP_name[k].territory}</td>
          <td>${data[i].HCO_name[j].HCP_name[k].pdrp}</td>
         </tr>`
        );
      }
    }
  }
};

// Adding filters

if ($("#region").val() === "All") {
  table(data1);
}

$(".filter").click(() => {
  let my_table = [];
  $(".table-body").html("");
  if ($("#region").val() === "All") {
    table(data1);
  }
  let sel_region = $("#region").val();
  let sel_territory = $("#territory").val();

  for (let x = 0; x < data1.length; x++) {
    for (let y = 0; y < data1[x].HCO_name.length; y++) {
      for (let z = 0; z < data1[x].HCO_name[y].HCP_name.length; z++) {
        if (
          (sel_territory === "all" &&
            data1[x].HCO_name[y].HCP_name[z].region === sel_region) ||
          (data1[x].HCO_name[y].HCP_name[z].region === sel_region &&
            data1[x].HCO_name[y].HCP_name[z].territory === sel_territory)
        ) {
          let new_ele = {};
          new_ele.PARENT_NAME = data1[x].parent_name;
          new_ele.CHILD_NAME = data1[x].HCO_name[y].name;
          new_ele.HCP_NAME = data1[x].HCO_name[y].HCP_name[z].hcp;
          new_ele.REGION = data1[x].HCO_name[y].HCP_name[z].region;
          new_ele.TERRITORY = data1[x].HCO_name[y].HCP_name[z].territory;
          new_ele.PDRP = data1[x].HCO_name[y].HCP_name[z].pdrp;
          my_table.push(new_ele);
        }
      }
    }
  }
  let filtered_data = d_frame(my_table);
  table(filtered_data);
  console.log(my_table);
});

// Collapsing event
let p_tab=-1
$("body").on("click", ".parent", (event) => {
  let id = event.target.id;
  console.log(id);
  if (p_tab!==id) {
    $(`#tab${id}`).show(300);
    $(`#btn${id}`).html("−");
    if(p_tab!==-1){
    $(`#tab${p_tab}`).hide();
    $(`#btn${id}`).html("+");}
    
    p_tab=id
  } else {
    $(`#tab${id}`).hide(300);
    $(`#btn${id}`).html("+");
    p_tab=-1
  }
});
let c_tab = -1;
$("body").on("click", ".child", (event) => {
  let id = event.target.id;
  console.log(id);
  if (c_tab !== id) {
    $(`#tab${id}`).show(300);
    $(`#btn${id}`).html("−");
    if(c_tab!==-1){
    $(`#tab${c_tab}`).hide();
    $(`#btn${id}`).html("+");}
    
    c_tab=id
  } else {
    $(`#tab${id}`).hide(300);
    $(`#btn${id}`).html("+");
    c_tab=-1
  }
});


// Logout function

$("#logout").click(()=>{
  window.location.href= "./signin_v_0_1_SS.html"
})